# Generated by Django 4.0 on 2022-03-13 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastprice',
            name='forecast_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
