# Generated by Django 4.0 on 2022-03-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0003_userfollowing_userforecast_userprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastprice',
            name='forecast_summary_T1',
            field=models.FloatField(),
        ),
    ]
