# Generated by Django 4.0 on 2022-03-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0004_alter_forecastprice_forecast_summary_t1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastprice',
            name='forecast_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastprice',
            name='forecast_eod_T1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastprice',
            name='forecast_high_T1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastprice',
            name='forecast_low_T1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastprice',
            name='forecast_summary_T1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserForecast',
        ),
    ]
