# Generated by Django 4.0 on 2022-03-31 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0005_alter_forecastprice_forecast_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBinary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_date', models.DateField()),
                ('movement', models.FloatField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.tickerlist')),
            ],
        ),
    ]
