# Generated by Django 4.0 on 2022-04-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0006_dailybinary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastprice',
            name='forecast_eod_T1',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='forecastprice',
            name='forecast_high_T1',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='forecastprice',
            name='forecast_low_T1',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
