# Generated by Django 4.0 on 2022-04-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0007_alter_forecastprice_forecast_eod_t1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastprice',
            name='forecast_eod_T1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='forecastprice',
            name='forecast_high_T1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='forecastprice',
            name='forecast_low_T1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='stockdb',
            name='eod_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stockdb',
            name='high_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stockdb',
            name='low_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stockdb',
            name='open_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
