# Generated by Django 4.0 on 2022-04-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0008_alter_forecastprice_forecast_eod_t1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdbbuffer',
            name='volumn',
        ),
        migrations.AlterField(
            model_name='stockdbbuffer',
            name='eod_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stockdbbuffer',
            name='high_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stockdbbuffer',
            name='low_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stockdbbuffer',
            name='open_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
