# Generated by Django 4.0 on 2022-04-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0009_remove_stockdbbuffer_volumn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdbbuffer',
            name='match_key',
        ),
        migrations.AddField(
            model_name='stockdbbuffer',
            name='volumn',
            field=models.BigIntegerField(default=100),
            preserve_default=False,
        ),
    ]
