# Generated by Django 4.0 on 2022-04-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0010_remove_stockdbbuffer_match_key_stockdbbuffer_volumn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastprice',
            name='forecast_eod_T1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='forecastprice',
            name='forecast_high_T1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='forecastprice',
            name='forecast_low_T1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockdb',
            name='eod_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockdb',
            name='high_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockdb',
            name='low_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockdb',
            name='open_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockdbbuffer',
            name='eod_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockdbbuffer',
            name='high_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockdbbuffer',
            name='low_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockdbbuffer',
            name='open_price',
            field=models.FloatField(),
        ),
    ]
