# Generated by Django 4.0 on 2022-04-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0013_userperformance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastprice',
            name='forecast_eod_T1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastprice',
            name='forecast_high_T1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastprice',
            name='forecast_low_T1',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
