# Generated by Django 4.0 on 2022-04-29 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0014_alter_forecastprice_forecast_eod_t1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-comment_time']},
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='dailybinary',
            old_name='movement',
            new_name='movement_T1',
        ),
        migrations.RenameField(
            model_name='forecastprice',
            old_name='forecast_date',
            new_name='forecast_date_T1',
        ),
        migrations.RenameField(
            model_name='userperformance',
            old_name='performance',
            new_name='performance_T1',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='post',
        ),
        migrations.AddField(
            model_name='comments',
            name='ticker',
            field=models.ForeignKey(default='TCB', on_delete=django.db.models.deletion.CASCADE, to='forecast.tickerlist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailybinary',
            name='movement_T3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forecastprice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='forecastprice',
            name='forecast_date_T3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forecastprice',
            name='forecast_eod_T3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forecastprice',
            name='forecast_movement_T3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forecastprice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tickerlist',
            name='comment_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tickerlist',
            name='forecast_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tickerlist',
            name='view_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='userperformance',
            name='performance_T3',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reputation',
            field=models.PositiveIntegerField(default=0, verbose_name='points'),
        ),
    ]
