# Generated by Django 4.0 on 2022-05-02 17:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0016_rename_comments_comment_rename_posts_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=40)),
                ('session', models.CharField(max_length=40)),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 5, 3, 0, 19, 25, 521672))),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickerviewcount', to='forecast.tickerlist')),
            ],
        ),
    ]
