# Generated by Django 4.0 on 2022-05-02 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0017_tickerviewcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickerviewcount',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 3, 0, 47, 20, 616811)),
        ),
        migrations.AlterField(
            model_name='tickerviewcount',
            name='session',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
