# Generated by Django 4.0 on 2022-05-02 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0018_alter_tickerviewcount_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickerviewcount',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 3, 0, 51, 58, 882164)),
        ),
        migrations.AlterField(
            model_name='tickerviewcount',
            name='session',
            field=models.CharField(default='asdfasfad23424ass', max_length=40),
            preserve_default=False,
        ),
    ]
