# Generated by Django 4.0 on 2022-05-07 14:55

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forecast', '0019_alter_tickerviewcount_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickerviewcount',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tickerviewcount',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 7, 21, 55, 38, 228874)),
        ),
    ]
