# Generated by Django 4.0 on 2022-05-07 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0020_tickerviewcount_user_alter_tickerviewcount_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickerviewcount',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 7, 22, 0, 54, 192223)),
        ),
        migrations.RemoveField(
            model_name='tickerviewcount',
            name='user',
        ),
        migrations.AddField(
            model_name='tickerviewcount',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
