# Generated by Django 4.0 on 2022-05-28 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0021_alter_tickerviewcount_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastprice',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='forecastprice',
            name='updated_times',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='forecastprice',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tickerviewcount',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 23, 10, 16, 241550)),
        ),
    ]
