# Generated by Django 4.0 on 2022-05-28 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0022_remove_forecastprice_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickerviewcount',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 23, 54, 16, 93027)),
        ),
    ]
