# Generated by Django 4.0 on 2022-05-28 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0023_alter_tickerviewcount_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastprice',
            name='updated_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tickerviewcount',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 0, 25, 38, 728069)),
        ),
    ]
