# Generated by Django 4.0 on 2022-07-13 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0024_alter_forecastprice_updated_times_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollowing',
            name='created',
        ),
        migrations.AlterField(
            model_name='tickerviewcount',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 13, 22, 22, 15, 221290)),
        ),
    ]
