# Generated by Django 4.0 on 2022-07-13 15:24

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0025_remove_userfollowing_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollowing',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tickerviewcount',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 13, 22, 23, 36, 694922)),
        ),
    ]
