# Generated by Django 4.0 on 2022-07-13 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0027_rename_following_user_id_userfollowing_follower_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickerviewcount',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 13, 23, 33, 7, 255682)),
        ),
    ]
