# Generated by Django 4.0 on 2022-07-17 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0029_userprofile_created_alter_tickerviewcount_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='reputation',
        ),
        migrations.AlterField(
            model_name='tickerviewcount',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 17, 17, 11, 18, 719109)),
        ),
    ]
