# Generated by Django 4.0 on 2022-07-17 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0030_remove_userprofile_reputation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickerviewcount',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 17, 19, 38, 5, 106068)),
        ),
    ]
