# Generated by Django 4.0 on 2022-07-22 00:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('forecast', '0031_alter_tickerviewcount_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickerviewcount',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 22, 7, 56, 58, 997197)),
        ),
        migrations.CreateModel(
            name='TickerFollowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('follower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticker_follower', to='auth.user')),
                ('ticker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticker_follow', to='forecast.tickerlist')),
            ],
            options={
                'unique_together': {('ticker_id', 'follower_id')},
            },
        ),
    ]
