# Generated by Django 4.0 on 2022-07-27 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0037_alter_tickerviewcount_created_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickerviewcount',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 0, 26, 15, 884107)),
        ),
    ]
