# Generated by Django 4.0 on 2022-07-30 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0039_alter_tickerviewcount_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickerviewcount',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 30, 15, 52, 6, 885972)),
        ),
    ]
