# Generated by Django 4.0 on 2022-08-22 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0053_alter_tickerviewcount_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateField(null=True)),
                ('forecast_date_T1', models.DateField(null=True)),
                ('forecast_date_T3', models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tickerviewcount',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 23, 29, 7, 589147)),
        ),
    ]
