# Generated by Django 4.0 on 2022-08-23 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0054_forecasttrigger_alter_tickerviewcount_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickerviewcount',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 23, 16, 15, 41, 716838)),
        ),
    ]
