# Generated by Django 4.0 on 2022-08-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0057_alter_tickerviewcount_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
